
package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ITDService", targetNamespace = "http://tempuri.org/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ITDService {


    /**
     * 
     * @param request
     * @return
     *     returns org.tempuri.TransitDeclarationResponse
     */
    @WebMethod(operationName = "RequestTD", action = "http://tempuri.org/ITDService/RequestTD")
    @WebResult(name = "RequestTDResult", targetNamespace = "http://tempuri.org/")
    @RequestWrapper(localName = "RequestTD", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestTD")
    @ResponseWrapper(localName = "RequestTDResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.RequestTDResponse")
    public TransitDeclarationResponse requestTD(
        @WebParam(name = "request", targetNamespace = "http://tempuri.org/")
        TDInfoRequest request);

}
