
package com.axelor.apps.navigation.integration.org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TDService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://212.112.104.124:8122/TDService?wsdl")
public class TDService
    extends Service
{

    private final static URL TDSERVICE_WSDL_LOCATION;
    private final static WebServiceException TDSERVICE_EXCEPTION;
    private final static QName TDSERVICE_QNAME = new QName("http://tempuri.org/", "TDService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://212.112.104.124:8122/TDService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TDSERVICE_WSDL_LOCATION = url;
        TDSERVICE_EXCEPTION = e;
    }

    public TDService() {
        super(__getWsdlLocation(), TDSERVICE_QNAME);
    }

    public TDService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TDSERVICE_QNAME, features);
    }

    public TDService(URL wsdlLocation) {
        super(wsdlLocation, TDSERVICE_QNAME);
    }

    public TDService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TDSERVICE_QNAME, features);
    }

    public TDService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TDService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ITDService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITDService")
    public ITDService getBasicHttpBindingITDService() {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITDService"), ITDService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ITDService
     */
    @WebEndpoint(name = "BasicHttpBinding_ITDService")
    public ITDService getBasicHttpBindingITDService(WebServiceFeature... features) {
        return super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_ITDService"), ITDService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TDSERVICE_EXCEPTION!= null) {
            throw TDSERVICE_EXCEPTION;
        }
        return TDSERVICE_WSDL_LOCATION;
    }

}
